name: tests+pypi

defaults:
  run:
    shell: bash

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 13 * * 4'
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-12, windows-latest]
        python-version: ["3.7", "3.8", "3.9"]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - run: |
          pip install -e .

      # sanity check if we do not depend on something from test-time-requirements.txt
      - run: |
          python -We -c "import PySDM"

      - run: |
          SYSTEM_VERSION_COMPAT=0 pip install -r test-time-requirements.txt

      # ensure previous pip did not overwrite the package
      - run: |
          pip install -e .

      # https://github.com/numba/numba/issues/6350#issuecomment-728174860
      - if: startsWith(matrix.platform, 'ubuntu-')
        run: echo NUMBA_THREADING_LAYER=omp >> $GITHUB_ENV

      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pytest -p no:unraisableexception -We

#       - if: ${{ failure() }}
#         uses: mxschmitt/action-tmate@v3
#         with:
#           limit-access-to-actor: true

  dist:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # https://github.com/pypa/setuptools_scm/issues/480
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - run: pip install twine build

      - run: |
          unset CI
          python -m build 2>&1 | tee build.log
          exit `fgrep -i warning build.log | grep -v impl_numba/warnings.py | wc -l`

      - run: twine check --strict dist/*

      - if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/

      - if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
